name: Deploy Angular App to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Detect Angular Project Name and Output Path
        id: detect-project
        run: |
          PROJECT_NAME=$(node -e "
            const fs = require('fs');
            const angular = JSON.parse(fs.readFileSync('angular.json', 'utf8'));
            const defaultProject = angular.defaultProject || Object.keys(angular.projects)[0];
            const outputPath = angular.projects[defaultProject].architect.build.options.outputPath;
            console.log(JSON.stringify({ projectName: defaultProject, outputPath: outputPath }));
          ")
          PROJECT_OUTPUT=$(echo $PROJECT_NAME | node -e "
            const input = JSON.parse(require('fs').readFileSync(0, 'utf8'));
            console.log(input.outputPath.replace('dist/', ''));
          ")
          echo "project-name=$(echo $PROJECT_NAME | node -e "const input = JSON.parse(require('fs').readFileSync(0, 'utf8')); console.log(input.projectName);")" >> $GITHUB_OUTPUT
          echo "output-folder=$PROJECT_OUTPUT" >> $GITHUB_OUTPUT
          echo "Detected Angular project: $(echo $PROJECT_NAME | node -e "const input = JSON.parse(require('fs').readFileSync(0, 'utf8')); console.log(input.projectName);")"
          echo "Output folder: $PROJECT_OUTPUT"

      - name: Build Angular App
        run: |
          npm run build -- --base-href "/${{ github.event.repository.name }}/"
          echo "Build completed for project: ${{ steps.detect-project.outputs.project-name }}"

      - name: Copy index.html to 404.html for SPA routing
        run: |
          OUTPUT_FOLDER="${{ steps.detect-project.outputs.output-folder }}"
          cp "dist/$OUTPUT_FOLDER/index.html" "dist/$OUTPUT_FOLDER/404.html"
          echo "Copied index.html to 404.html for SPA routing support"

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/${{ steps.detect-project.outputs.output-folder }}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4